name: FantasyMinecraft
version: '${version}'
description: '${description}'
main: by.telir.fantasyminecraft.FantasyMinecraft

commands:
  rc:
    description: "Reloading Server"
  debug:
  fly:
    permission: "command.fly"

  user:
    usage: /<command> [args]
  attribute:
    usage: /<command> <attribute>

  geffect:
    usage: /<command> <effect>