name: FantasyMinecraft
version: '${version}'
description: '${description}'
main: by.telir.fantasyminecraft.FantasyMinecraft

commands:
  rc:
    usage: /<command>
    description: "Reloading Server"

  user:
    usage: /<command> [args]
  attribute:
    usage: /<command> <attribute>